<<<<<<< HEAD
# Generated by Django 4.2.1 on 2023-07-31 08:45
=======
# Generated by Django 4.2.1 on 2023-07-27 13:19
>>>>>>> 3b863214f796e66470316d24c4829e269910068f

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

<<<<<<< HEAD
    dependencies = [
    ]
=======
    dependencies = []
>>>>>>> 3b863214f796e66470316d24c4829e269910068f

    operations = [
        migrations.CreateModel(
            name='Clientregistration',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.CharField(max_length=14)),
                ('city', models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Navi Mumbai', 'Navi Mumbai'), ('Thane', 'Thane'), ('Pune', 'Pune'), ('Bangaluru', 'Bangaluru'), ('Delhi', 'Delhi')], default='Mumbai', max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=200, null=True)),
                ("mobile_number", models.CharField(max_length=14)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("alternet_number", models.BigIntegerField()),
>>>>>>> 3b863214f796e66470316d24c4829e269910068f
            ],
        ),
        migrations.CreateModel(
            name='PlaceBooking',
            fields=[
<<<<<<< HEAD
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_type', models.CharField(blank=True, max_length=50, null=True)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('car_type', models.CharField(max_length=100, null=True)),
                ('gear_type', models.CharField(max_length=100, null=True)),
                ('pickup_location', models.CharField(max_length=100, null=True)),
                ('drop_location', models.CharField(max_length=100, null=True)),
                ('booking_time', models.DateTimeField(auto_now_add=True)),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.clientregistration')),
=======
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_curr_lat", models.FloatField()),
                ("user_curr_long", models.FloatField()),
                ("from_date", models.DateField()),
                ("to_date", models.DateField()),
                ("car_type", models.CharField(max_length=100, null=True)),
                ("gear_type", models.CharField(max_length=100, null=True)),
                ("pickup_location", models.CharField(max_length=100, null=True)),
                ("drop_location", models.CharField(max_length=100, null=True)),
                ("booking_time", models.DateTimeField(auto_now_add=True)),
                (
                    "client_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.clientregistration",
                    ),
                ),
>>>>>>> 3b863214f796e66470316d24c4829e269910068f
            ],
        ),
    ]
