# Generated by Django 4.2.1 on 2023-07-15 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.BigIntegerField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('alternet_number', models.BigIntegerField()),
            ],
        ),
    ]
