# Generated by Django 4.2.1 on 2023-07-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebooking',
            name='packege',
            field=models.CharField(choices=[('4Hours', '4Hours'), ('8Hours', '8Hours'), ('Night', 'Night')], default='4Hours', max_length=20),
        ),
        migrations.AddField(
            model_name='placebooking',
            name='trip_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
