# Generated by Django 4.2.1 on 2023-07-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientregistration",
            name="mobile_number",
            field=models.CharField(max_length=14),
        ),
    ]
