# Generated by Django 4.2.1 on 2023-07-26 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placebooking',
            name='client_name',
        ),
        migrations.DeleteModel(
            name='Clientregistration',
        ),
    ]
