# Generated by Django 4.2.1 on 2023-08-29 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebooking',
            name='accepted_driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_driver', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='placebooking',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('decline', 'decline'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
