# Generated by Django 4.2.1 on 2023-08-11 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0001_initial'),
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_favourite', models.BooleanField(default=False)),
                ('invoice_generate', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver_management.adddriver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.bookinguser')),
            ],
        ),
    ]
