# Generated by Django 4.2.1 on 2023-07-26 11:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_remove_placebooking_client_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientregistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mobile_number', models.BigIntegerField()),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('alternet_number', models.BigIntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientregistration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
