# Generated by Django 4.2.1 on 2023-07-15 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_clientregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placebooking',
            name='client_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.clientregistration'),
        ),
    ]
