# Generated by Django 4.2.1 on 2023-08-03 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_placebooking_client_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placebooking',
            old_name='client_name',
            new_name='user',
        ),
    ]
