# Generated by Django 4.2.1 on 2023-08-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_invoice_invoicenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoicenumber',
            field=models.IntegerField(blank=True, null=True, verbose_name=0),
        ),
    ]
