# Generated by Django 4.2.1 on 2023-07-26 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0003_clientregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientregistration',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clientregistration', to=settings.AUTH_USER_MODEL),
        ),
    ]
