# Generated by Django 4.2.1 on 2023-07-21 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_placebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placebooking',
            name='packege',
            field=models.CharField(choices=[('4Hours', '4Hours'), ('8Hours', '8Hours'), ('Night', 'Night')], default='4Hours', max_length=20),
        ),
    ]
