# Generated by Django 4.2.1 on 2023-07-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_clientregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebooking',
            name='client_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='booking.clientregistration'),
            preserve_default=False,
        ),
    ]
