# Generated by Django 4.2.1 on 2023-07-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_placebooking_packege'),
    ]

    operations = [
        migrations.RenameField(
            model_name='placebooking',
            old_name='packege',
            new_name='package',
        ),
    ]
