# Generated by Django 4.2.1 on 2023-07-15 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_remove_placebooking_coupon_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placebooking',
            name='currunt_loaction',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
