# Generated by Django 4.2.1 on 2023-07-26 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_placebooking_packege'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placebooking',
            name='driver',
        ),
        migrations.AlterField(
            model_name='placebooking',
            name='packege',
            field=models.CharField(default='4Hours', max_length=20),
        ),
    ]
