# Generated by Django 4.2.1 on 2023-07-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_placebooking_client_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientregistration',
            name='user',
        ),
    ]
