# Generated by Django 4.2.1 on 2023-07-19 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0001_initial'),
        ('booking', '0005_alter_placebooking_currunt_loaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placebooking',
            name='drop_location',
        ),
        migrations.RemoveField(
            model_name='placebooking',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='placebooking',
            name='driver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='driver_management.adddriver'),
            preserve_default=False,
        ),
    ]
