# Generated by Django 4.2.1 on 2023-07-20 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_placebooking_drop_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='placebooking',
            name='drop_location',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='placebooking',
            name='pickup_location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
