# Generated by Django 4.2.1 on 2023-08-04 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user',
            field=models.CharField(blank=True, choices=[('Customer', 'Customer'), ('Driver', 'Driver')], max_length=100, null=True),
        ),
    ]
