# Generated by Django 4.2.1 on 2023-08-03 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='is_active',
            new_name='is_user',
        ),
    ]
