# Generated by Django 4.2.1 on 2023-08-29 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='state_code',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
