# Generated by Django 4.2.1 on 2023-07-11 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user_master", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.country"
            ),
        ),
        migrations.AlterField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.country"
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.country"
            ),
        ),
        migrations.AlterField(
            model_name="state",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.country"
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.country"
            ),
        ),
        migrations.AlterField(
            model_name="zonemapping",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.country"
            ),
        ),
    ]
