# Generated by Django 4.2.1 on 2023-07-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0002_alter_branch_country_alter_city_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermaster',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='email_id',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
