# Generated by Django 4.2.1 on 2023-07-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0004_alter_usermaster_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Temprory', 'Temprory'), ('Permanent', 'Permanent'), ('Reqruit', 'Reqruit')], null=True),
        ),
    ]
