# Generated by Django 4.2.1 on 2023-07-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_master', '0005_alter_usermaster_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='role',
            field=models.CharField(blank=True, choices=[('Admin', 'Admin'), ('Temprory', 'Temprory'), ('Permanent', 'Permanent'), ('Recruit', 'Recruit')], null=True),
        ),
    ]
