# Generated by Django 4.2.1 on 2023-05-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("driver_management", "0001_initial"),
        ("user_master", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="adddriver",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.branch"
            ),
        ),
        migrations.AddField(
            model_name="adddriver",
            name="city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.city"
            ),
        ),
        migrations.AddField(
            model_name="adddriver",
            name="location",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.location"
            ),
        ),
        migrations.AddField(
            model_name="adddriver",
            name="state",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.state"
            ),
        ),
        migrations.AddField(
            model_name="adddriver",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="user_master.zone"
            ),
        ),
    ]
