# Generated by Django 4.2.1 on 2023-07-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbalance',
            name='pay',
            field=models.PositiveBigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Driverleave',
        ),
    ]
