# Generated by Django 4.2.1 on 2023-07-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddriver',
            name='driver_rating',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
