# Generated by Django 4.2.1 on 2023-07-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddriver',
            name='Current_latitude_location',
        ),
        migrations.RemoveField(
            model_name='adddriver',
            name='Current_longitude_location',
        ),
    ]
