# Generated by Django 4.2.1 on 2023-08-26 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0002_alter_adddriver_driver_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddriver',
            name='region',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
