# Generated by Django 4.2.1 on 2023-07-14 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0002_driverbalance_pay_delete_driverleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverbalance',
            name='drivername',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='driver_management.adddriver'),
            preserve_default=False,
        ),
    ]
