# Generated by Django 4.2.1 on 2023-07-24 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0002_remove_adddriver_current_latitude_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddriver',
            name='Purchase_uniform',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='car_transmission',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Luxury', 'Luxury')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='car_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Luxury', 'Luxury'), ('Hatchback', 'Hatchback'), ('MVP', 'MPV'), ('MUV', 'MUV')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='cast',
            field=models.CharField(choices=[('Marathi', 'Marathi'), ('Muslim', 'Muslim'), ('Gujrati', 'Gujarati'), ('SO', 'SouthIndian'), ('Punjabi', 'Punjabi'), ('UP', 'UP'), ('Bihari', 'Bihari'), ('Other', 'Other')], default='MA', max_length=20),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='driver_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='driving_status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='heavy_vehicle',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='is_approval_done',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='language',
            field=models.CharField(choices=[('Hindi', 'Hindi'), ('English', 'English'), ('Bhojpuri', 'Bhojpuri')], default='Hindi', max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='licence_type',
            field=models.CharField(choices=[('LMV-TR', 'LMV-TR'), ('LMV-NT', 'LMV-NT')], default='TR', max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='marital_status',
            field=models.CharField(choices=[('Married', 'Married'), ('Single', 'Single')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='passport',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='police_verification',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='qualification',
            field=models.CharField(choices=[('5', '5th'), ('6', '6th'), ('7', '7th'), ('8', '8th'), ('9', '9th'), ('SSC', 'SSC'), ('HSC', 'HSC'), ('BC', 'BCOM'), ('BS', 'BSc'), ('BE', 'BE'), ('BA', 'BA')], default='SS', max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim', 'Muslim'), ('Christian', 'Christian'), ('Sikh', 'Sikh')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='schedule_training',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='scheduled_driving_test',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='scheme_type',
            field=models.CharField(choices=[('Platinum', 'Platinum'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='sex',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='training_status',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='transmission_type',
            field=models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic'), ('Luxury', 'Luxury')], max_length=10),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='week_off',
            field=models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=10),
        ),
    ]
