# Generated by Django 4.2.1 on 2023-07-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0002_adddriver_driver_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='adddriver',
            name='Current_latitude_location',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adddriver',
            name='Current_longitude_location',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
