# Generated by Django 4.2.1 on 2023-07-24 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0003_alter_adddriver_purchase_uniform_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddriver',
            name='blood_group',
            field=models.CharField(choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=10),
        ),
    ]
