# Generated by Django 4.2.1 on 2023-08-19 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0003_alter_adddriver_image_upload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adddriver',
            name='driver_user',
        ),
    ]
