# Generated by Django 4.2.1 on 2023-07-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0004_driverleave'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverleave',
            name='leave_from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driverleave',
            name='leave_to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
