# Generated by Django 4.2.1 on 2023-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0005_driverlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='driver_lat',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='driver_long',
            field=models.DecimalField(decimal_places=5, max_digits=5),
        ),
    ]
