# Generated by Django 4.2.1 on 2023-07-14 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0005_driverleave_leave_from_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverleave',
            name='total_days_of_leave',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
