# Generated by Django 4.2.1 on 2023-07-25 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0006_alter_driverlocation_driver_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverlocation',
            name='driver_lat',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
        migrations.AlterField(
            model_name='driverlocation',
            name='driver_long',
            field=models.DecimalField(decimal_places=7, max_digits=7),
        ),
    ]
