# Generated by Django 4.2.1 on 2023-07-25 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0009_alter_driverlocation_driver_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddriver',
            name='address_location',
            field=models.CharField(max_length=100),
        ),
    ]
