# Generated by Django 4.2.1 on 2023-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver_management', '0010_alter_adddriver_address_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddriver',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='adddriver',
            name='car_type',
            field=models.CharField(choices=[('SUV', 'SUV'), ('Sedan', 'Sedan'), ('Luxury', 'Luxury'), ('Hatchback', 'Hatchback'), ('MPV', 'MPV'), ('MUV', 'MUV')], max_length=10),
        ),
    ]
